apiVersion: v1
kind: Service
metadata:
  name: {{ include "rpc-listener-service.fullname" . }}
  labels:
    {{- include "rpc-listener-service.labels" . | nindent 4 }}
  
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rpc-listener-service.selectorLabels" . | nindent 4 }}
